package zornco.megax.client.entities;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.src.*;
public class ModelTurret extends ModelBase
{
  //fields
    ModelRenderer BottomBase;
    ModelRenderer MidBase;
    ModelRenderer TopBase;
    ModelRenderer Head;
    ModelRenderer Shnozz;
    ModelRenderer LeftTusk;
    ModelRenderer RightTusk;
    ModelRenderer Neck;
    ModelRenderer MainBody;
    ModelRenderer LowerBody;
    ModelRenderer UpperRightLeg;
    ModelRenderer LowerRightLeg;
    ModelRenderer UpperLeftLeg;
    ModelRenderer LowerLeftLeg;
    ModelRenderer UpperLeftArm;
    ModelRenderer LowerLeftArm;
    ModelRenderer UpperRightArm;
    ModelRenderer LowerRightArm;
    ModelRenderer MainShield;
    ModelRenderer FrontShieldEmblem;
    ModelRenderer FrontShieldUpperLower;
    ModelRenderer FrontShieldLower;
    ModelRenderer RightShield;
    ModelRenderer RightShieldConvex;
    ModelRenderer LeftShield;
    ModelRenderer LeftShieldConvex;
    ModelRenderer SwordHilt;
    ModelRenderer UpperSwordHilt;
    ModelRenderer Blade;
    ModelRenderer LowerRightBlade;
    ModelRenderer LowerLeftBlade;
    ModelRenderer BladeCrystal;
    ModelRenderer UpperRightBlade;
    ModelRenderer UpperLeftBlade;
    ModelRenderer UpperBlade;
 
  public ModelTurret()
  {
    textureWidth = 128;
    textureHeight = 128;
   
      BottomBase = new ModelRenderer(this, 0, 0);
      BottomBase.addBox(0F, 0F, 0F, 28, 7, 28);
      BottomBase.setRotationPoint(-6F, 17F, -6F);
      BottomBase.setTextureSize(128, 128);
      BottomBase.mirror = true;
      setRotation(BottomBase, 0F, 0F, 0F);
      MidBase = new ModelRenderer(this, 0, 35);
      MidBase.addBox(0F, 0F, 0F, 24, 6, 24);
      MidBase.setRotationPoint(-4F, 13F, -4F);
      MidBase.setTextureSize(128, 128);
      MidBase.mirror = true;
      setRotation(MidBase, 0F, 0F, 0F);
      TopBase = new ModelRenderer(this, 0, 65);
      TopBase.addBox(0F, 0F, 0F, 22, 2, 22);
      TopBase.setRotationPoint(-3F, 11F, -3F);
      TopBase.setTextureSize(128, 128);
      TopBase.mirror = true;
      setRotation(TopBase, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 51, 90);
      Head.addBox(0F, 0F, 0F, 7, 6, 6);
      Head.setRotationPoint(20F, -18F, 5F);
      Head.setTextureSize(128, 128);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0.7853982F);
      Shnozz = new ModelRenderer(this, 51, 102);
      Shnozz.addBox(0F, 0F, 0F, 5, 3, 4);
      Shnozz.setRotationPoint(22F, -13F, 6F);
      Shnozz.setTextureSize(128, 128);
      Shnozz.mirror = true;
      setRotation(Shnozz, 0F, 0F, 0F);
      LeftTusk = new ModelRenderer(this, 52, 90);
      LeftTusk.addBox(0F, 0F, 0F, 1, 4, 1);
      LeftTusk.setRotationPoint(25F, -16F, 11F);
      LeftTusk.setTextureSize(128, 128);
      LeftTusk.mirror = true;
      setRotation(LeftTusk, 0F, 0F, 0.7853982F);
      RightTusk = new ModelRenderer(this, 72, 90);
      RightTusk.addBox(0F, 0F, 0F, 1, 4, 1);
      RightTusk.setRotationPoint(25F, -16F, 4F);
      RightTusk.setTextureSize(128, 128);
      RightTusk.mirror = true;
      setRotation(RightTusk, 0F, 0F, 0.7853982F);
      Neck = new ModelRenderer(this, 77, 91);
      Neck.addBox(0F, 0F, 0F, 17, 5, 6);
      Neck.setRotationPoint(2F, -17F, 5F);
      Neck.setTextureSize(128, 128);
      Neck.mirror = true;
      setRotation(Neck, 0F, 0F, 0F);
      MainBody = new ModelRenderer(this, 3, 92);
      MainBody.addBox(0F, 0F, 0F, 15, 17, 18);
      MainBody.setRotationPoint(1F, -15F, -1F);
      MainBody.setTextureSize(128, 128);
      MainBody.mirror = true;
      setRotation(MainBody, 0F, 0F, 0F);
      LowerBody = new ModelRenderer(this, 69, 108);
      LowerBody.addBox(0F, 0F, 0F, 12, 3, 16);
      LowerBody.setRotationPoint(3F, 2F, 0F);
      LowerBody.setTextureSize(128, 128);
      LowerBody.mirror = true;
      setRotation(LowerBody, 0F, 0F, 0F);
      UpperRightLeg = new ModelRenderer(this, 11, 36);
      UpperRightLeg.addBox(0F, 0F, 0F, 3, 6, 3);
      UpperRightLeg.setRotationPoint(9.066667F, 5F, 1F);
      UpperRightLeg.setTextureSize(128, 128);
      UpperRightLeg.mirror = true;
      setRotation(UpperRightLeg, 0F, 0F, 0F);
      LowerRightLeg = new ModelRenderer(this, 3, 45);
      LowerRightLeg.addBox(0F, 0F, 0F, 7, 3, 3);
      LowerRightLeg.setRotationPoint(2F, 8F, 1F);
      LowerRightLeg.setTextureSize(128, 128);
      LowerRightLeg.mirror = true;
      setRotation(LowerRightLeg, 0F, 0F, 0F);
      UpperLeftLeg = new ModelRenderer(this, 1, 66);
      UpperLeftLeg.addBox(0F, 0F, 0F, 7, 3, 3);
      UpperLeftLeg.setRotationPoint(9F, 5F, 12F);
      UpperLeftLeg.setTextureSize(128, 128);
      UpperLeftLeg.mirror = true;
      setRotation(UpperLeftLeg, 0F, 0F, 0F);
      LowerLeftLeg = new ModelRenderer(this, 9, 72);
      LowerLeftLeg.addBox(0F, 0F, 0F, 3, 3, 3);
      LowerLeftLeg.setRotationPoint(13F, 8F, 12F);
      LowerLeftLeg.setTextureSize(128, 128);
      LowerLeftLeg.mirror = true;
      setRotation(LowerLeftLeg, 0F, 0F, 0F);
      UpperLeftArm = new ModelRenderer(this, 72, 36);
      UpperLeftArm.addBox(-3F, 0F, 0F, 6, 11, 5);
      UpperLeftArm.setRotationPoint(9F, -13F, 17F);
      UpperLeftArm.setTextureSize(128, 128);
      UpperLeftArm.mirror = true;
      setRotation(UpperLeftArm, 0F, 0F, -0.7853982F);
      LowerLeftArm = new ModelRenderer(this, 94, 36);
      LowerLeftArm.addBox(0F, 0F, -2F, 12, 5, 5);
      LowerLeftArm.setRotationPoint(16.5F, -7.5F, 20F);
      LowerLeftArm.setTextureSize(128, 128);
      LowerLeftArm.mirror = true;
      setRotation(LowerLeftArm, 0F, 0.7853982F, 0F);
      UpperRightArm = new ModelRenderer(this, 98, 56);
      UpperRightArm.addBox(0F, 0F, 0F, 6, 11, 5);
      UpperRightArm.setRotationPoint(9F, -13F, -6F);
      UpperRightArm.setTextureSize(128, 128);
      UpperRightArm.mirror = true;
      setRotation(UpperRightArm, 0F, 0F, 0F);
      LowerRightArm = new ModelRenderer(this, 94, 46);
      LowerRightArm.addBox(0F, 0F, 0F, 12, 5, 5);
      LowerRightArm.setRotationPoint(15F, -7F, -6F);
      LowerRightArm.setTextureSize(128, 128);
      LowerRightArm.mirror = true;
      setRotation(LowerRightArm, 0F, 0F, 0F);
      MainShield = new ModelRenderer(this, 86, 0);
      MainShield.addBox(0F, 0F, 0F, 14, 17, 3);
      MainShield.setRotationPoint(20F, -13F, 20F);
      MainShield.setTextureSize(128, 128);
      MainShield.mirror = true;
      setRotation(MainShield, 0F, 0.7853982F, 0F);
      FrontShieldEmblem = new ModelRenderer(this, 86, 20);
      FrontShieldEmblem.addBox(0F, 0F, 0F, 7, 7, 1);
      FrontShieldEmblem.setRotationPoint(24.5F, -10F, 19.5F);
      FrontShieldEmblem.setTextureSize(128, 128);
      FrontShieldEmblem.mirror = true;
      setRotation(FrontShieldEmblem, 0F, 0.7853982F, 0F);
      FrontShieldUpperLower = new ModelRenderer(this, 102, 20);
      FrontShieldUpperLower.addBox(0F, 0F, 0F, 11, 3, 2);
      FrontShieldUpperLower.setRotationPoint(21F, 4F, 19F);
      FrontShieldUpperLower.setTextureSize(128, 128);
      FrontShieldUpperLower.mirror = true;
      setRotation(FrontShieldUpperLower, 0F, 0.7853982F, 0F);
      FrontShieldLower = new ModelRenderer(this, 103, 25);
      FrontShieldLower.addBox(0F, 0F, 0F, 7, 2, 1);
      FrontShieldLower.setRotationPoint(23F, 7F, 17F);
      FrontShieldLower.setTextureSize(128, 128);
      FrontShieldLower.mirror = true;
      setRotation(FrontShieldLower, 0F, 0.7853982F, 0F);
      RightShield = new ModelRenderer(this, 0, 90);
      RightShield.addBox(-4F, -4F, -2F, 8, 8, 2);
      RightShield.setRotationPoint(12F, -12F, -5F);
      RightShield.setTextureSize(128, 128);
      RightShield.mirror = true;
      setRotation(RightShield, -0.6981317F, 0F, 0F);
      RightShieldConvex = new ModelRenderer(this, 6, 100);
      RightShieldConvex.addBox(-4F, -4F, -2F, 6, 6, 1);
      RightShieldConvex.setRotationPoint(13F, -12F, -6F);
      RightShieldConvex.setTextureSize(128, 128);
      RightShieldConvex.mirror = true;
      setRotation(RightShieldConvex, -0.6981317F, 0F, 0F);
      LeftShield = new ModelRenderer(this, 66, 69);
      LeftShield.addBox(-4F, -4F, 0F, 8, 8, 2);
      LeftShield.setRotationPoint(9F, -14F, 22F);
      LeftShield.setTextureSize(128, 128);
      LeftShield.mirror = true;
      setRotation(LeftShield, -2.443461F, 0F, -0.6981317F);
      LeftShieldConvex = new ModelRenderer(this, 72, 79);
      LeftShieldConvex.addBox(-3F, -3F, 0F, 6, 6, 1);
      LeftShieldConvex.setRotationPoint(8.5F, -14.5F, 22.5F);
      LeftShieldConvex.setTextureSize(128, 128);
      LeftShieldConvex.mirror = true;
      setRotation(LeftShieldConvex, -2.443461F, 0F, -0.6981317F);
      SwordHilt = new ModelRenderer(this, 0, 13);
      SwordHilt.addBox(0F, 0F, 0F, 2, 1, 4);
      SwordHilt.setRotationPoint(24F, -8F, -5.5F);
      SwordHilt.setTextureSize(128, 128);
      SwordHilt.mirror = true;
      setRotation(SwordHilt, 0F, 0F, 0F);
      UpperSwordHilt = new ModelRenderer(this, 108, 29);
      UpperSwordHilt.addBox(0F, 0F, 0F, 4, 1, 6);
      UpperSwordHilt.setRotationPoint(23F, -9F, -6.5F);
      UpperSwordHilt.setTextureSize(128, 128);
      UpperSwordHilt.mirror = true;
      setRotation(UpperSwordHilt, 0F, 0F, 0F);
      Blade = new ModelRenderer(this, 0, 30);
      Blade.addBox(0F, 0F, 0F, 1, 4, 5);
      Blade.setRotationPoint(24.5F, -12.06667F, -6F);
      Blade.setTextureSize(128, 128);
      Blade.mirror = true;
      setRotation(Blade, 0F, 0F, 0F);
      LowerRightBlade = new ModelRenderer(this, 11, 0);
      LowerRightBlade.addBox(0F, 0F, 0F, 1, 13, 3);
      LowerRightBlade.setRotationPoint(24.5F, -23F, -10F);
      LowerRightBlade.setTextureSize(128, 128);
      LowerRightBlade.mirror = true;
      setRotation(LowerRightBlade, 0.3490659F, 0F, 0F);
      LowerLeftBlade = new ModelRenderer(this, 19, 0);
      LowerLeftBlade.addBox(0F, 0F, 0F, 1, 13, 3);
      LowerLeftBlade.setRotationPoint(24.5F, -24F, 0F);
      LowerLeftBlade.setTextureSize(128, 128);
      LowerLeftBlade.mirror = true;
      setRotation(LowerLeftBlade, -0.3490659F, 0F, 0F);
      BladeCrystal = new ModelRenderer(this, 11, 52);
      BladeCrystal.addBox(0F, 0F, 0F, 3, 3, 3);
      BladeCrystal.setRotationPoint(22F, -23F, -4F);
      BladeCrystal.setTextureSize(128, 128);
      BladeCrystal.mirror = true;
      setRotation(BladeCrystal, 0.7853982F, 0.7853982F, 0F);
      UpperRightBlade = new ModelRenderer(this, 11, 0);
      UpperRightBlade.addBox(0F, 0F, 0F, 1, 14, 3);
      UpperRightBlade.setRotationPoint(24.5F, -36F, -5.2F);
      UpperRightBlade.setTextureSize(128, 128);
      UpperRightBlade.mirror = true;
      setRotation(UpperRightBlade, -0.3490659F, 0F, 0F);
      UpperLeftBlade = new ModelRenderer(this, 19, 0);
      UpperLeftBlade.addBox(0F, 0F, 0F, 1, 14, 3);
      UpperLeftBlade.setRotationPoint(24.5F, -35F, -4.7F);
      UpperLeftBlade.setTextureSize(128, 128);
      UpperLeftBlade.mirror = true;
      setRotation(UpperLeftBlade, 0.3490659F, 0F, 0F);
      UpperBlade = new ModelRenderer(this, 19, 18);
      UpperBlade.addBox(0F, 0F, 0F, 1, 3, 3);
      UpperBlade.setRotationPoint(24.5F, -36F, -5.6F);
      UpperBlade.setTextureSize(128, 128);
      UpperBlade.mirror = true;
      setRotation(UpperBlade, 0.7853982F, 0F, 0F);
  }
 
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    BottomBase.render(f5);
    MidBase.render(f5);
    TopBase.render(f5);
    Head.render(f5);
    Shnozz.render(f5);
    LeftTusk.render(f5);
    RightTusk.render(f5);
    Neck.render(f5);
    MainBody.render(f5);
    LowerBody.render(f5);
    UpperRightLeg.render(f5);
    LowerRightLeg.render(f5);
    UpperLeftLeg.render(f5);
    LowerLeftLeg.render(f5);
    UpperLeftArm.render(f5);
    LowerLeftArm.render(f5);
    UpperRightArm.render(f5);
    LowerRightArm.render(f5);
    MainShield.render(f5);
    FrontShieldEmblem.render(f5);
    FrontShieldUpperLower.render(f5);
    FrontShieldLower.render(f5);
    RightShield.render(f5);
    RightShieldConvex.render(f5);
    LeftShield.render(f5);
    LeftShieldConvex.render(f5);
    SwordHilt.render(f5);
    UpperSwordHilt.render(f5);
    Blade.render(f5);
    LowerRightBlade.render(f5);
    LowerLeftBlade.render(f5);
    BladeCrystal.render(f5);
    UpperRightBlade.render(f5);
    UpperLeftBlade.render(f5);
    UpperBlade.render(f5);
  }
 
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
 
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity par7Entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, par7Entity);
  }
 
}